'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {projectIndex,verifiedDeployment,attentionState,healthSummary} from '../lib/contracts.mjs';
import {Row,Resource,resources,show,pick,status,request} from './runtime';
import {CreateForm} from './Forms';
import {Chip,Panel,Empty,Table,ResponsibilityList} from './Widgets';
import Surfaces from './Surfaces';
const groups: [string,[string,string,string][]][]=[
  ['Command',[['Dashboard','/console/dashboard','◫'],['Command','/console/command','⌘']]],
  ['Operations',[['Projects','/projects','▦'],['Responsibilities','/responsibilities','◎'],['Work Orders','/work-orders','▤'],['Delegation','/delegation','⇄'],['Tasks','/tasks','☷'],['Workflows','/workflows','⤳']]],
  ['Intelligence',[["Oru’Valen",'/oruvalen','◈'],['OMOS','/omos','◇'],['Agents','/agents','♙'],['Providers','/delegation/providers','▧']]],
  ['Control',[['Executions','/executions','▷'],['Approvals','/approvals','✓'],['Connections','/connections','⌁']]],
  ['Engineering',[['Engineering Council','/engineering-council','⌑'],['Deployments','/deployments','↗'],['Verification','/verification','⊙']]],
  ['Governance',[['Audit','/audit','≡'],['System Status','/status','◉']]],
  ['Administration',[['Documentation','/docs','▣'],['Settings','/settings','⚙'],['Account','/account','○']]],
];
export default function Console({path,user}:{path:string[];user:{name:string;email:string}}){
  const [data,setData]=useState<Record<string,Resource>>(()=>Object.fromEntries(resources.map(r=>[r,{rows:[],error:null,loading:true,raw:null}]))),[refresh,setRefresh]=useState(0),[menu,setMenu]=useState(false),[form,setForm]=useState(false);
  useEffect(()=>{let alive=true;for(const resource of resources){request(resource).then(raw=>{if(alive)setData(d=>({...d,[resource]:{rows:Array.isArray(raw)?raw:[],raw,error:null,loading:false}}));}).catch(error=>{if(alive)setData(d=>({...d,[resource]:{rows:[],raw:null,error:error.message,loading:false}}));});}return ()=>{alive=false;};},[refresh]);
  function reload(){setData(Object.fromEntries(resources.map(r=>[r,{rows:[],error:null,loading:true,raw:null}])));setRefresh(n=>n+1);}
  const rows=(key:string)=>data[key]?.rows??[];
  const work=rows('work-orders'),responsibilities=rows('responsibilities'),projects=projectIndex(work,responsibilities) as Row[];
  const current='/'+path.join('/'),page=path[0]==='console'?path[1]:path[0],isProviders=page==='models'||(page==='delegation'&&path[1]==='providers');
  const title=isProviders?'Execution Providers':groups.flatMap(g=>g[1]).find(n=>n[1]===current)?.[0]??(page==='projects'?'Project Control Center':page==='work-orders'?'Work Order':page==='responsibilities'?'Responsibility':page);
  const failed=resources.filter(k=>!!data[k]?.error).length,loading=!Object.keys(data).length||resources.some(k=>data[k]?.loading);
  const count=(key:string,predicate:(r:Row)=>boolean)=>!data[key]||data[key]?.loading||data[key]?.error?'—':String(rows(key).filter(predicate).length);
  const verified=(r:Row)=>verifiedDeployment(r,rows('verification'));
  const health=healthSummary(data.health?.raw);
  const kpis=[['Active Projects','Unknown','▦'],['Active Responsibilities',count('responsibilities',r=>status(r)==='ACTIVE'),'◎'],['Open Work Orders',count('work-orders',r=>!['COMPLETED','CANCELLED'].includes(status(r))),'▤'],['Work Orders Running',count('work-orders',r=>status(r)==='RUNNING'),'▷'],['Awaiting Human Approval',count('approvals',r=>status(r)==='PENDING'),'✓'],['Blocked Work',count('work-orders',r=>status(r)==='BLOCKED'),'⊘'],['Failed Executions',count('executions',r=>status(r)==='FAILED'),'!'],['Deployments Pending Verification',!data.verification||data.verification.loading||data.verification.error?'—':count('deployments',r=>!verified(r)),'↗'],['Provider Health',health.providers,'⌁'],['System Health',health.system,'◉']];
  const attention:Row[]=[...rows('approvals').filter(r=>status(r)==='PENDING').map(r=>({...r,attentionKind:'Approval awaiting decision',href:'/approvals'})),...work.filter(r=>status(r)==='BLOCKED').map(r=>({...r,attentionKind:'Blocked work order',href:'/work-orders/'+r.id})),...rows('executions').filter(r=>status(r)==='FAILED').map(r=>({...r,attentionKind:'Failed execution',href:'/executions'})),...rows('connections').filter(r=>['UNHEALTHY','FAILED','DEGRADED'].includes(show(r.health).toUpperCase())).map(r=>({...r,attentionKind:'Unhealthy connection',href:'/connections'})),...rows('deployments').filter(r=>!verified(r)).map(r=>({...r,attentionKind:'Deployment awaiting verification',href:'/verification'}))];
  const unknownState=attentionState(data);
  function dashboard(){return <><div className="overview-heading"><div><span className="eyebrow">OPERATIONAL OVERVIEW</span><h1>Your work. Your authority.</h1><p>Exceptions first. Decisions next. Every action leaves evidence.</p></div><div className="date-box"><span>DEVELOPMENT TRACK</span><strong>ACC V2 <small>α.1</small></strong></div></div><div className="kpi-grid">{kpis.map(([label,value,icon])=><div className="kpi" key={label}><div><span>{label}</span><b>{icon}</b></div><strong>{value}</strong><small>{value==='—'||value==='Unknown'?'Evidence unavailable':label==='Active Projects'?'Active state not exposed':'Reported by ACC runtime'}</small></div>)}</div><div className="dashboard-grid"><Panel title="Needs My Attention" meta="DECISIONS & EXCEPTIONS"><div className="attention-intro"><span className="amber-dot"/><span>Human authority precedes execution</span></div>{attention.length?attention.map((r,i)=><Link className="attention-row" key={i} href={show(r.href)}><span className="attention-symbol">!</span><div><strong>{show(r.attentionKind)}</strong><small>{show(pick(r,'objective','requested_action','name','id'))}</small></div><Chip value={r.status}/><span>↗</span></Link>):<Empty state={unknownState} label="exceptions"/>}</Panel><Panel title="Authority & release" meta="GOVERNED BY DESIGN"><div className="authority-card"><span className="shield">◇</span><h3>Human final authority</h3><p>Human → Oru / OMOS decision support → ACC → governed execution</p><hr/><div><span>Production baseline</span><b>v1.3.0</b></div><div><span>V2 source branch</span><b>2.0.0-alpha.1</b></div><div><span>Canonical verification</span><Chip value="Unknown"/></div><Link href="/docs">Release criteria & rollback →</Link></div></Panel></div><Panel title="Active Work" meta="PROJECT → WORK ORDER → PROVIDER"><Table rows={work.filter(r=>['RUNNING','QUEUED','READY','AWAITING_APPROVAL'].includes(status(r)))} state={data['work-orders']} kind="work-orders"/></Panel><Panel title="Persistent Responsibilities" meta="ONGOING OPERATIONAL OWNERSHIP"><ResponsibilityList list={responsibilities.filter(r=>status(r)==='ACTIVE')} state={data.responsibilities}/></Panel><Panel title="Recent Results" meta="COMPLETION REQUIRES EVIDENCE"><Table rows={[...work.filter(r=>status(r)==='COMPLETED'),...rows('deployments').filter(verified),...rows('approvals').filter(r=>['APPROVED','REJECTED'].includes(status(r)))]} state={failed?unknownState:undefined} kind="results"/></Panel></>;}
  return <div className="console-shell"><aside className={'sidebar '+(menu?'open':'')}><Link href="/console/dashboard" className="brand"><span className="brand-emblem">A<span>◇</span></span><div><strong>ACC<span>™</span></strong><small>ONEGODIAN COMMAND</small></div><span className="version-tag">V2</span></Link><div className="workspace"><span className="workspace-icon">O</span><div><strong>OneGodian</strong><small>Operator workspace</small></div><span>⌄</span></div><nav aria-label="Primary operator navigation">{groups.map(([group,items])=><div className="nav-group" key={group}><h2>{group}</h2>{items.map(([label,href,icon])=><Link key={href} href={href} onClick={()=>setMenu(false)} aria-current={current===href?'page':undefined} className={current===href||(href==='/projects'&&page==='projects')||(href==='/work-orders'&&page==='work-orders')||(href==='/responsibilities'&&page==='responsibilities')?'active':''}><span>{icon}</span>{label}{label==='Approvals'&&rows('approvals').some(r=>status(r)==='PENDING')&&<b>{rows('approvals').filter(r=>status(r)==='PENDING').length}</b>}</Link>)}</div>)}</nav><div className="sidebar-bottom"><span className="avatar">{user.name.slice(0,1).toUpperCase()}</span><div><strong>{user.name}</strong><small>Human operator</small></div><Link href="/account" aria-label="Operator account">↗</Link></div></aside>{menu&&<button className="backdrop" aria-label="Close navigation" onClick={()=>setMenu(false)}/>}
    <div className="main-column"><header className="topbar"><button className="mobile-menu" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>☰</button><div className="breadcrumb">ACC <span>/</span> <strong>{title}</strong></div><div className="topbar-actions"><span className="topbar-status"><i/> Runtime: {loading?'Loading':failed?'Unknown':'Evidence received'}</span><button className="icon-button" title="Refresh runtime evidence" aria-label="Refresh runtime evidence" onClick={reload}>↻</button><Link href="/approvals" className="icon-button" aria-label="Human approvals">♧</Link><span className="avatar small">{user.name.slice(0,1)}</span></div></header><main className="console-main"><div className="page-toolbar"><span className="eyebrow">ACC / {page==='dashboard'?'COMMAND':isProviders?'INTELLIGENCE':page.replaceAll('-',' ').toUpperCase()}</span><div><Chip value="Pre-release"/>{['work-orders','responsibilities','command'].includes(page)&&<button className="button compact" onClick={()=>setForm(true)}>+ {page==='responsibilities'?'Responsibility':'Work Order'}</button>}</div></div>{page!=='dashboard'&&<div className="page-heading"><h1>{title}</h1><p>Project-centered operations. Evidence-backed decisions.</p></div>}{failed>0&&<div className="runtime-banner" role="status"><span>⌁</span><div><strong>Runtime evidence is unavailable</strong><p>{data['work-orders']?.error??'One or more ACC services could not be reached.'} No operational status is inferred.</p></div><Link href="/connections">Connections ↗</Link></div>}{page==='dashboard'?dashboard():<Surfaces page={page} path={path} title={title} data={data} projects={projects} user={user} openForm={()=>setForm(true)} refresh={reload}/>}<footer className="console-footer"><span>ACC™ · ONEGODIAN, LLC · Human final authority</span><span>V2 α.1 frontend · Production baseline v1.3.0</span></footer></main></div>{form&&<CreateForm kind={page==='responsibilities'&&!path[1]?'responsibilities':'work-orders'} projectId={page==='projects'?path[1]:undefined} responsibilityId={page==='responsibilities'?path[1]:undefined} onClose={()=>setForm(false)} onSaved={()=>{setForm(false);reload();}}/>}</div>;
}
