'use client';
import {useEffect,useRef,useState} from 'react';
import {PROVIDERS} from '../lib/contracts.mjs';
import {Row,request,show} from './runtime';

export function CreateForm({kind,projectId,responsibilityId,onClose,onSaved}:{kind:string;projectId?:string;responsibilityId?:string;onClose:()=>void;onSaved:()=>void}){
  const [error,setError]=useState(''),[saving,setSaving]=useState(false);const dialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const element=dialog.current;element?.showModal();return ()=>element?.close();},[]);
  async function submit(event:React.FormEvent<HTMLFormElement>){
    event.preventDefault();setSaving(true);setError('');const values=new FormData(event.currentTarget);const value=(k:string)=>String(values.get(k)??'').trim();
    try{
      const parse=(k:string)=>value(k)?JSON.parse(value(k)):undefined;
      const lists=(k:string)=>value(k).split('\n').map(s=>s.trim()).filter(Boolean);
      const common={projectId:value('projectId'),provider:value('provider'),requiresHumanApproval:values.get('approval')==='on'};
      const payload=kind==='responsibilities'?{...common,name:value('name'),description:value('description'),ownerId:value('ownerId'),cadence:value('cadence')||'manual',triggers:parse('triggers')??[],status:'DRAFT'}:{...common,objective:value('objective'),responsibilityId:value('responsibilityId')||undefined,assignedTo:value('assignedTo')||undefined,executorRef:value('executorRef')||undefined,context:parse('context')??{},riskLevel:value('riskLevel'),requiredTools:lists('requiredTools'),files:lists('files'),dependencies:lists('dependencies'),schedule:parse('schedule')??null,trigger:parse('trigger')??null};
      await request(kind,{method:'POST',body:JSON.stringify(payload)});onSaved();
    }catch(e){setError(e instanceof Error?e.message:'Creation failed.');}finally{setSaving(false);}
  }
  const input=(label:string,name:string,required=false,initial?:string)=><label className="stacked-label" key={name}>{label}<input name={name} required={required} defaultValue={initial}/></label>;
  const area=(label:string,name:string,placeholder?:string)=><label className="stacked-label" key={name}>{label}<textarea name={name} placeholder={placeholder} rows={3}/></label>;
  return <dialog ref={dialog} className="form-dialog" onCancel={onClose}><form onSubmit={submit}><div className="panel-head"><div><span className="eyebrow">GOVERNED INTAKE</span><h2>New {kind==='responsibilities'?'Responsibility':'Work Order'}</h2></div><button type="button" className="icon-button" aria-label="Close form" onClick={onClose}>×</button></div><p className="section-note">Creates a {kind==='responsibilities'?'DRAFT responsibility':'PLANNED Work Order'} in canonical ACC. This does not authorize or execute work.</p><div className="form-grid">{input('Project ID','projectId',true,projectId)}{kind==='responsibilities'?<>{input('Name','name',true)}{input('Owner ID','ownerId',true)}{input('Cadence','cadence',false,'manual')}{area('Description','description')}{area('Trigger definitions (JSON array)','triggers','[]')}</>:<>{input('Responsibility ID','responsibilityId',false,responsibilityId)}{input('Objective','objective',true)}{input('Assigned to','assignedTo')}{input('Executor reference','executorRef')}{area('Context (JSON object)','context','{}')}<label className="stacked-label">Risk level<select name="riskLevel">{['LOW','MEDIUM','HIGH','CRITICAL'].map(r=><option key={r}>{r}</option>)}</select></label>{area('Required tools (one per line)','requiredTools')}{area('Files (one per line)','files')}{area('Dependencies (one per line)','dependencies')}{area('Schedule (JSON object)','schedule','{}')}{area('Trigger (JSON object)','trigger','{}')}</>}<label className="stacked-label">Preferred execution provider<select name="provider">{PROVIDERS.map(p=><option key={p.id} value={p.id}>{p.label} · {p.maturity}</option>)}</select></label><label className="check-label"><input type="checkbox" name="approval" defaultChecked/>Requires human approval</label></div>{error&&<div className="form-error" role="alert">{error}</div>}<div className="form-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button" disabled={saving}>{saving?'Submitting…':'Create governed record'}</button></div></form></dialog>;
}
export function ApprovalDecision({row,onSaved}:{row:Row;onSaved:()=>void}){
  const [reason,setReason]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  async function decide(decision:string){setBusy(true);setMessage('');try{await request(`approvals/${encodeURIComponent(show(row.id))}/decide`,{method:'POST',body:JSON.stringify({decision,reason})});onSaved();}catch(e){setMessage(e instanceof Error?e.message:'Decision failed.');}finally{setBusy(false);}}
  if(row.status!=='PENDING')return <p className="section-note">Decision recorded by ACC: {show(row.decided_by)} · {show(row.decided_at)}</p>;
  return <div className="approval-controls"><label className="stacked-label">Decision reason<textarea aria-label="Approval decision reason" value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="form-actions"><button className="button" disabled={busy||!reason.trim()} onClick={()=>decide('APPROVED')}>Approve</button><button className="button danger" disabled={busy||!reason.trim()} onClick={()=>decide('REJECTED')}>Reject</button><button className="button secondary" disabled title="Request Changes requires a separate governed backend decision endpoint">Request Changes · unavailable</button></div>{message&&<p role="alert" className="form-error">{message}</p>}<p className="meta">Submits a separate governed decision; no optimistic approval or Work Order status update.</p></div>;
}
