'use client';
import {useState} from 'react';
import Link from 'next/link';
import {PROVIDERS,providerPresentation,verifiedDeployment} from '../lib/contracts.mjs';
import {Row,Resource,show,pick,status} from './runtime';
import {Chip,Panel,Empty,Table,EvidenceFields} from './Widgets';
import {ApprovalDecision} from './Forms';
const projectTabs=['Overview','Responsibilities','Work Orders','Agents','Workflows','Executions','Approvals','Artifacts','Deployments','Verification','Audit','Connections','Settings'];
const timeline=['Created','Validated','Authorized','Queued','Assigned','Executed','Tool Calls','Output','Approval','Verification','Deployment','Final Status'];
const workFields=[['Work Order ID','id'],['Project','project_id'],['Responsibility','responsibility_id'],['Objective','objective'],['Context','context'],['Requested by','requested_by'],['Assigned to','assigned_to'],['Execution provider','provider'],['Executor reference','executor_ref'],['Risk level','risk_level'],['Human approval requirement','requires_human_approval'],['Status','status'],['Required tools','required_tools'],['Files','files'],['Dependencies','dependencies'],['Schedule','schedule'],['Trigger','trigger'],['Artifacts','artifacts'],['Verification','verification'],['Deployment evidence','deployment_evidence'],['Created timestamp','created_at'],['Updated timestamp','updated_at']];
const responsibilityFields=[['Responsibility ID','id'],['Project','project_id'],['Name','name'],['Description','description'],['Owner','owner_id'],['Preferred provider','provider'],['Status','status'],['Cadence','cadence'],['Trigger definitions','triggers'],['Requires human approval','requires_human_approval'],['Last Work Order','last_work_order'],['Next expected execution','next_expected_execution'],['Created','created_at'],['Updated','updated_at']];
const fields=(keys:string[])=>keys.map(k=>[k.replaceAll('_',' '),k]);
const Flow=({items}:{items:string[]})=><div className="flow">{items.map((s,i)=><div key={s}><small>{String(i+1).padStart(2,'0')}</small><strong>{s}</strong><span>↓</span></div>)}</div>;
export default function Surfaces({page,path,title,data,projects,user,openForm,refresh}:{page:string;path:string[];title:string;data:Record<string,Resource>;projects:Row[];user:{name:string;email:string};openForm:()=>void;refresh:()=>void}){
  const [tab,setTab]=useState('Overview'),[selection,setSelection]=useState('');
  const rows=(key:string)=>data[key]?.rows??[],work=rows('work-orders');
  const record=rows(page).find(r=>show(r.id)===path[1]);const projectId=path[1];
  const scoped=(key:string)=>rows(key).filter(r=>show(pick(r,'project_id','projectId'))===projectId);
  if(page==='models'||(page==='delegation'&&path[1]==='providers'))return <><div className="section-note"><strong>Provider maturity is separate from work status.</strong><p>Registry definitions describe intended capability. Connection, health, and execution availability require runtime evidence.</p></div><div className="provider-grid">{PROVIDERS.map(def=>{const evidence=rows('execution-providers').find(r=>r.id===def.id);const p=providerPresentation(def.id,evidence);return <section className={'provider-card '+(def.id==='openai-dot'?'reserved':'')} key={def.id}><div className="provider-head"><span className="provider-icon">{def.category==='human'?'○':'◇'}</span><Chip value={p.maturity}/></div><h2>{p.label}</h2><code>{p.id}</code><p>{def.notes}</p><EvidenceFields row={{...p,capabilities:evidence?.capabilities,work_order_types:evidence?.supportedWorkOrderTypes,approval:'ACC policy / applicable human gate',executable:def.id==='openai-dot'?false:evidence?p.executable:'Unknown'}} fields={[["Provider class","category"],["Executable","executable"],["Connection state","connectionState"],["Health","health"],["Last activity","lastActivity"],["Capabilities","capabilities"],["Supported Work Order types","work_order_types"],["Approval requirements","approval"]]}/><div className="card-footer">{def.id==='openai-dot'?'Reserved Provider — Execution Not Available':evidence?'Registry definition received; runtime health requires evidence':'Runtime evidence: Unknown'}</div></section>;})}</div></>;
  if(['work-orders','responsibilities'].includes(page)){
    if(path[1]){if(!record)return <Panel title={title}><Empty state={data[page]} label="matching records"/></Panel>;
      const details={...record};if(page==='responsibilities'){const related=work.filter(r=>r.responsibility_id===record.id);details.last_work_order=related.at(0)?.id??record.last_work_order;}
      return <><div className="detail-banner"><div><code>{show(record.id)}</code><h2>{show(pick(record,'objective','name'))}</h2></div><Chip value={record.status}/></div><Panel title="Record & evidence"><EvidenceFields row={details} fields={page==='work-orders'?workFields:responsibilityFields}/></Panel>{page==='work-orders'?<><Panel title="One execution trace" meta="EVENTS ARE NEVER INFERRED"><div className="trace">{timeline.map(s=><div key={s}><span className="trace-dot"/><strong>{s}</strong><small>{s==='Created'?show(record.created_at):'Evidence required'}</small></div>)}</div><p className="section-note">The foundation API does not expose a correlated event timeline. These stages define the required contract, not asserted events.</p><EvidenceFields row={record} fields={['project_id','responsibility_id','work_order_id','provider_id','execution_id','approval_id','verification_id','deployment_id'].map(k=>[k,k==='work_order_id'?'id':k==='provider_id'?'provider':k])}/></Panel><Panel title="Approval authority"><p className="section-note">Approval satisfaction comes only from the governed approval system. Work Order editing cannot grant approval.</p><Link className="button" href="/approvals">Open Approval Center →</Link></Panel></>:<Panel title="Work Orders produced by this responsibility"><Table rows={work.filter(r=>r.responsibility_id===record.id)} state={data['work-orders']} kind="work-orders"/><button className="button" onClick={openForm}>Prepare another Work Order</button></Panel>}</>;
    }
    return <><div className="section-note"><strong>{page==='work-orders'?'An auditable unit of governed work.':'Ongoing ownership, producing multiple Work Orders over time.'}</strong><p>{page==='work-orders'?'PLANNED → READY → QUEUED → RUNNING → AWAITING APPROVAL → COMPLETED · BLOCKED / FAILED / CANCELLED':'DRAFT · ACTIVE · PAUSED · BLOCKED · ARCHIVED'}</p></div><Panel title={title}><Table rows={rows(page)} state={data[page]} kind={page}/></Panel>{page==='responsibilities'&&<Panel title="Responsibility examples" meta="TEMPLATES — NOT LIVE RECORDS"><div className="template-grid">{['Maintain ACC production health.','Review Algonquian Real Estate acquisition pipeline.','Maintain ALLATYME platform deployment readiness.','Monitor unresolved engineering work.'].map(s=><div key={s}><span>◎</span><strong>{s}</strong></div>)}</div></Panel>}</>;
  }
  if(page==='projects'){
    if(!projectId)return <><p className="section-note">Projects are indexed from persisted Work Order and Responsibility references. First-class project metadata and settings are not exposed by the V2 foundation API.</p><div className="project-grid">{projects.map(p=><Link className="project-card" key={show(p.id)} href={'/projects/'+encodeURIComponent(show(p.id))}><span className="project-icon">▦</span><Chip value="Unknown"/><h2>{show(p.name)}</h2><p>{show(p.source)}</p><div><span>{work.filter(r=>r.project_id===p.id).length} work orders</span><b>Open control center ↗</b></div></Link>)}</div>{!projects.length&&<Panel title="Project index"><Empty state={data['work-orders']} label="project references"/></Panel>}</>;
    const tabResource=tab.toLowerCase().replace(' ','-');const metric=(key:string,predicate:(r:Row)=>boolean)=>!data[key]||data[key].loading||data[key].error?'Unknown':String(scoped(key).filter(predicate).length);
    return <><div className="detail-banner"><div><span className="eyebrow">PROJECT CONTROL CENTER</span><h2>{projectId}</h2></div><Chip value="Unknown"/></div><div className="project-tabs" role="tablist" aria-label="Project sections">{projectTabs.map(t=><button key={t} role="tab" aria-selected={tab===t} className={tab===t?'selected':''} onClick={()=>setTab(t)} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const index=projectTabs.indexOf(t);const next=e.key==='Home'?0:e.key==='End'?projectTabs.length-1:(index+(e.key==='ArrowRight'?1:-1)+projectTabs.length)%projectTabs.length;setTab(projectTabs[next]);const buttons=e.currentTarget.parentElement?.querySelectorAll('button');buttons?.[next]?.focus();}}}>{t}</button>)}</div><div role="tabpanel" aria-label={tab}>{tab==='Overview'?<><div className="summary-grid">{[['Purpose','Project objective metadata unavailable'],['Responsibilities',metric('responsibilities',()=>true)],['Work happening now',metric('work-orders',r=>['RUNNING','QUEUED'].includes(status(r)))],['Human attention',metric('work-orders',r=>['BLOCKED','AWAITING_APPROVAL'].includes(status(r)))],['Completed work',metric('work-orders',r=>status(r)==='COMPLETED')],['Failed work',metric('work-orders',r=>status(r)==='FAILED')],['Actually deployed',!data.verification||data.verification.loading||data.verification.error||rows('deployments').some(r=>!r.project_id)?'Unknown':metric('deployments',r=>verifiedDeployment(r,rows('verification')))]].map(([k,v])=><div className="summary-card" key={k}><span>{k}</span><strong>{v}</strong></div>)}</div><Panel title="Active Work"><Table rows={scoped('work-orders')} state={data['work-orders']} kind="work-orders"/></Panel></>:tab==='Artifacts'?<Panel title="Project artifacts"><Table rows={scoped('work-orders').flatMap(r=>Array.isArray(r.artifacts)?r.artifacts.filter(a=>typeof a==='object'&&a!==null) as Row[]:[])} state={data['work-orders']} kind="artifacts"/></Panel>:tab==='Settings'?<Panel title="Project settings"><p className="section-note">Editing is unavailable until a governed first-class project API exists.</p></Panel>:<Panel title={tab}><Table rows={scoped(tabResource)} state={data[tabResource]} kind={tabResource}/></Panel>}</div></>;
  }
  if(page==='delegation'){const selected=work.find(r=>r.id===selection),provider=selected?providerPresentation(show(selected.provider),rows('execution-providers').find(r=>r.id===selected.provider)):undefined;return <><Flow items={['Project','Responsibility','Work Order','Provider Selection','Authorization','Execution','Verification','Result']}/><Panel title="Inspect provider selection" meta="UNKNOWN PROVIDERS FAIL CLOSED"><label className="stacked-label">Work Order<select value={selection} onChange={e=>setSelection(e.target.value)}><option value="">Select a recorded Work Order</option>{work.map(r=><option key={show(r.id)} value={show(r.id)}>{show(r.objective)}</option>)}</select></label>{selected?<EvidenceFields row={{requested_provider:selected.provider,selected_provider:selected.selected_provider,capability_match:selected.capability_match,availability:provider?.evidenceAvailable?provider.executable?'Executable definition':'Non-executable':'Unknown',authorization_result:selected.authorization_result,fallback_eligibility:selected.fallback_eligibility,execution_target:selected.executor_ref}} fields={fields(['requested_provider','selected_provider','capability_match','availability','authorization_result','fallback_eligibility','execution_target'])}/>:<Empty state={data['work-orders']} label="selected work orders"/>}<p className="section-note">Selection reasons, authorization, and fallback eligibility require ACC records. No silent rerouting or frontend dispatch.</p></Panel><Link className="button" href="/delegation/providers">View execution providers →</Link></>;}
  if(page==='approvals')return <><p className="section-note">Decisions use the separate governed approval endpoint. Work Order linkage and Request Changes are not yet supplied by the foundation backend.</p>{!rows('approvals').length?<Panel title="Awaiting human decision"><Empty state={data.approvals} label="approval requests"/></Panel>:rows('approvals').map(r=><Panel key={show(r.id)} title={show(r.requested_action)} meta={show(r.id)}><EvidenceFields row={r} fields={[["Work Order","work_order_id"],["Project","project_id"],["Requesting provider / agent","requesting_agent"],["Requested action","requested_action"],["Affected resource","affected_resource"],["Risk level","risk_level"],["Policy","policy"],["Reason","reason"],["Supporting evidence","evidence"],["Requested timestamp","created_at"],["Decision","status"],["Decision record","decision_reason"]]}/><ApprovalDecision row={r} onSaved={refresh}/></Panel>)}</>;
  if(['oruvalen','omos'].includes(page)){const oru=page==='oruvalen',areas=oru?['Proposed Work Orders','Proposed Responsibilities','Context Used','Decision Evidence','Outcome','Learning Proposal','Human Accepted / Rejected']:['Runtime status','Reasoning requests','Decision records','Context references','Provider routing','Human Gate status','ACC Work Order reference','Execution result','Verification evidence'];return <><div className="integration-hero"><span className="eyebrow">{oru?'OPERATIONAL INTELLIGENCE TWIN':'GOVERNED REASONING'}</span><h2>{oru?'Prepare work. Preserve human authority.':'Reasoning supports governed execution.'}</h2><p>Human → Oru / OMOS decision support → ACC → governed execution</p><Chip value="External"/><span className="meta"> Integration runtime: Unknown</span></div><div className="summary-grid">{areas.map(f=><Panel key={f} title={f}><p className="section-note">Unknown — no authenticated integration evidence is available for this field.</p></Panel>)}</div>{oru&&<a className="button" href="/OruValen-Guide.txt" download="OruValen Guide.txt">Download OruValen Guide.txt ↓</a>}<Panel title="Work prepared through ACC"><p className="section-note">Context → proposed responsibility / work → Work Order → ACC authorization → provider → execution → verified outcome → learning proposal. Learning remains a proposal until accepted by an authorized human.</p><Link className="button" href="/work-orders">Open Work Orders →</Link></Panel></>;}
  if(page==='connections'){const classes=['Model','Data','Action','Environment'],getClass=(r:Row)=>show(pick(r,'connection_class','class','type')).toLowerCase();return <>{classes.map(c=><Panel key={c} title={c+' Connections'} meta="READ / WRITE / APPROVAL"><div className="connection-grid">{rows('connections').filter(r=>getClass(r)===c.toLowerCase()).map(r=><div className="connection-card" key={show(r.id)}><h3>{show(pick(r,'name','id'))}</h3><EvidenceFields row={r} fields={fields(['adapter','protocol','auth_state','capabilities','read_permissions','write_permissions','approval_requirement','environment','health','last_successful_operation','rate_limit','audit_policy','verification_policy'])}/></div>)}</div>{!rows('connections').some(r=>getClass(r)===c.toLowerCase())&&<Empty state={data.connections} label={c.toLowerCase()+' connections'}/>}</Panel>)}{rows('connections').some(r=>!classes.some(c=>getClass(r)===c.toLowerCase()))&&<Panel title="Unclassified connections"><Table rows={rows('connections').filter(r=>!classes.some(c=>getClass(r)===c.toLowerCase()))} kind="connections"/></Panel>}</>;}
  if(page==='engineering-council')return <><Flow items={['Issue','Engineering Work Order','Assignment','Implementation','Pull Request','Review','Tests','Human Approval','Merge','Deploy','Production Verification']}/><Panel title="Engineering Work Orders"><p className="section-note">A merged Pull Request is not a verified deployment. Engineering completion requires production verification evidence. No completion is inferred from merge state.</p><Table rows={work.filter(r=>/engineering|pull request|repo|deploy|code/i.test(show(r.objective)))} state={data['work-orders']} kind="work-orders"/></Panel></>;
  if(page==='command')return <Panel title="Prepare governed work"><p className="section-note">Begin with a project objective. Define scope, context, risk, tools, dependencies, provider, and required approval before execution.</p><button className="button" onClick={openForm}>Prepare Work Order +</button><Flow items={['Project','Responsibility','Work Order','Delegation','Authorization','Execution','Verification','Deployment','Audit']}/></Panel>;
  if(page==='status')return <><div className="summary-grid">{['System Health','Provider Health','PostgreSQL','API Authentication','Queue','Canonical Deployment'].map(s=><Panel title={s} key={s}><Chip value="Unknown"/><p className="section-note">Runtime evidence required.</p></Panel>)}</div><Panel title="Raw authenticated health evidence"><pre>{data.health?.error??show(data.health?.raw)}</pre></Panel></>;
  if(page==='docs')return <><Panel title="ACC V2 architecture"><p className="section-note">Projects → Responsibilities → Work Orders → Delegation → Execution → Approval → Verification → Deployment → Audit</p><div className="doc-links"><a href="/OruValen-Guide.txt" download="OruValen Guide.txt">OruValen Guide.txt <span>↓</span></a><a href="/ACC-V2-Developer-Board.txt" download>Developer task board & implementation coverage <span>↓</span></a><a href="/ACC-V2-Release-Runbook.txt" download>Deployment, integration & rollback runbook <span>↓</span></a><a href="https://github.com/ohi-stack/acc/tree/feat/acc-v2-delegation-foundation" target="_blank" rel="noreferrer">Canonical V2 source branch <span>↗</span></a></div></Panel><Panel title="Definition of Done"><p className="section-note">Implemented → Connected → Tested → Documented → Repeatable → Built → Deployed → Verified on acc.onegodian.com → Rollback-capable</p><p className="section-note">This frontend is a V2 prerelease surface. Runtime integration, canonical-domain verification and backend gaps remain release gates. Production baseline is v1.3.0.</p></Panel></>;
  if(page==='settings')return <Panel title="Server-bound configuration"><EvidenceFields row={{version:'2.0.0-alpha.1',baseline:'v1.3.0',origin:'ACC_API_ORIGIN (server-only)',credentials:'ACC_API_KEY (secret; server-only)',operator:'ACC_OPERATOR_EMAILS (server-only allowlist)',persistence:'Canonical ACC PostgreSQL',authority:'Authenticated backend policy',runtime:data.health?.error?'Unavailable':'Unknown until verified'}} fields={fields(['version','baseline','origin','credentials','operator','persistence','authority','runtime'])}/><p className="section-note">Configuration is managed through the hosting environment. No credentials are stored in browser bundles.</p></Panel>;
  if(page==='account')return <Panel title="Authenticated operator"><EvidenceFields row={{name:user.name,email:user.email,authority:'ACC authorization policy; no browser role override'}} fields={fields(['name','email','authority'])}/><Link className="button" href="/signout-with-chatgpt?return_to=%2F" prefetch={false}>Sign out →</Link></Panel>;
  return <><p className="section-note">{page==='agents'?'Agents are bounded executors beneath Projects and Work Orders.':page==='deployments'?'Deployment records require verification evidence before being represented as verified results.':page==='audit'?'Correlate project_id, responsibility_id, work_order_id, provider_id, execution_id, approval_id, verification_id and deployment_id.':'State is read from the governed ACC runtime.'}</p><Panel title={title}><Table rows={rows(page)} state={data[page]} kind={page}/></Panel></>;
}
