'use client';
import {useState} from 'react';
import Link from 'next/link';
import {Row,Resource,show,pick,status,elapsed} from './runtime';
export function Chip({value}:{value:unknown}){const text=show(value);return <span className={'chip chip-'+text.toLowerCase().replace(/[^a-z]/g,'')}>{text.replaceAll('_',' ')}</span>;}
export function Panel({title,meta,children}:{title:string;meta?:string;children:React.ReactNode}){return <section className="panel"><div className="panel-head"><h2>{title}</h2>{meta&&<span className="meta">{meta}</span>}</div>{children}</section>;}
export function EvidenceFields({row,fields}:{row:Row;fields:string[][]}){return <dl className="fields">{fields.map(([label,key])=><div key={key}><dt>{label}</dt><dd>{key==='status'?<Chip value={row[key]}/>:<span>{show(row[key])}</span>}</dd></div>)}</dl>;}
export function Empty({state,label}:{state?:Resource;label:string}){return <div className="empty" role="status"><span className="empty-icon">{state?.error?'⌁':'◎'}</span><strong>{state?.loading?'Loading runtime evidence…':state?.error?'Runtime evidence unavailable':`No ${label} recorded`}</strong><p>{state?.error??(state?.loading?'Retrieving authenticated ACC records.':'Records appear here when the governed ACC runtime returns them.')}</p>{state?.error&&<Link href="/connections">Inspect connections →</Link>}</div>;}
export function Table({rows,state,kind}:{rows:Row[];state?:Resource;kind:string}){
  const [query,setQuery]=useState(''),[filter,setFilter]=useState('ALL');const statuses=[...new Set(rows.map(status))];
  const filtered=rows.filter(r=>(filter==='ALL'||status(r)===filter)&&JSON.stringify(r).toLowerCase().includes(query.toLowerCase()));
  return <><div className="table-tools"><label className="search"><span>⌕</span><input aria-label={`Search ${kind}`} placeholder={`Search ${kind.replaceAll('-',' ')}…`} value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filter by status" value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">All states</option>{statuses.map(s=><option key={s}>{s}</option>)}</select><span className="meta">{state?.error?'Unknown':`${filtered.length} records`}</span></div>{!filtered.length?<Empty state={state} label={kind}/>:<div className="table-scroll"><table><thead><tr><th>{kind==='responsibilities'?'Responsibility':'Work / record'}</th><th>Project</th><th>Provider</th><th>Status</th><th>Risk / cadence</th><th>Elapsed</th></tr></thead><tbody>{filtered.map((r,i)=><tr key={show(r.id)+i}><td>{['work-orders','responsibilities','projects'].includes(kind)?<Link className="record-link" href={`/${kind}/${encodeURIComponent(show(r.id))}`}>{show(pick(r,'objective','name','requested_action','id'))}</Link>:<details><summary>{show(pick(r,'name','requested_action','action','id'))}</summary><pre>{show(r)}</pre></details>}<small>{show(r.id)}</small></td><td>{show(pick(r,'project_id','projectId'))}</td><td>{show(pick(r,'provider','requesting_agent','model_adapter'))}</td><td><Chip value={r.status}/></td><td>{show(pick(r,'risk_level','cadence'))}</td><td>{elapsed(r)}</td></tr>)}</tbody></table></div>}</>;
}
export function ResponsibilityList({list,state}:{list:Row[];state?:Resource}){return !list.length?<Empty state={state} label="responsibilities"/>:<div className="table-scroll"><table><thead><tr>{['Responsibility','Project','Owner','Provider','Cadence','Next action','Status'].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{list.map(r=><tr key={show(r.id)}><td><Link href={'/responsibilities/'+encodeURIComponent(show(r.id))}>{show(r.name)}</Link></td>{['project_id','owner_id','provider','cadence','next_expected_execution'].map(k=><td key={k}>{show(r[k])}</td>)}<td><Chip value={r.status}/></td></tr>)}</tbody></table></div>;}
